name: PR Merge Notifier

on:
  pull_request:
    types: [closed]  # only triggers when a PR is closed
    branches: [main]

jobs:
  notify:
    if: github.event.pull_request.merged == true  # ensure it's a merge, not just closed
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request on PR merge
        run: |
          curl -X POST https://your-endpoint.example.com \
            -H "Content-Type: application/json" \
            -d '{"message": "PR merged into main!", "pr_number": "${{ github.event.pull_request.number }}"}'
